from datetime import datetime
import enum
from typing import TYPE_CHECKING
from sqlalchemy import DateTime, Enum, ForeignKey, Interval, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.base import BaseModel
from app.functions import generate_uuid

if TYPE_CHECKING:
    from app.blueprints.vendor.model import Vendor
    from app.blueprints.well.model import Well

class OrderStatus(enum.Enum):
    PENDING = "pending"
    ASSIGNED = "assigned"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class PriorityStatus(enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"

#work order id is a string because it will be a uuid generated by the backend, not an auto-incrementing integer. 
# This is for better scalability and uniqueness
class WorkOrder(BaseModel):
    __tablename__ = "work_orders"

    work_order_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=generate_uuid,
    )

    assigned_vendor: Mapped[str | None] = mapped_column(
        ForeignKey("vendor.vendor_id"),
        nullable=True,
    )

    assigned_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        nullable=True,
    )

    description: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
    )

    due_date: Mapped[datetime | None] = mapped_column(
        DateTime,
        nullable=True,
    )

    estimated_start_date: Mapped[datetime | None] = mapped_column(
        DateTime,
        nullable=True,
    )

    estimated_end_date: Mapped[datetime | None] = mapped_column(
        DateTime,
        nullable=True,
    )

    current_status: Mapped[OrderStatus] = mapped_column(
        Enum(OrderStatus, name="order_status"),
        nullable=False,
    )
    priority: Mapped[PriorityStatus] = mapped_column(
        Enum(PriorityStatus, name="priority_status"),
        nullable=False,
    )

    comments: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
    )
    location: Mapped[str | None] = mapped_column(
        String(60),
        nullable=True,
    )

    estimated_cost: Mapped[Numeric | None] = mapped_column(
        Numeric,
        nullable=True,
    )
    estimated_duration: Mapped[Interval | None] = mapped_column(
        Interval,
        nullable=True,
    )

    well_id: Mapped[str | None] = mapped_column(
        ForeignKey("well.well_id"),
        nullable=True,
    )

    # Override BaseModel's nullable updated_by
    updated_by: Mapped[str] = mapped_column(
        ForeignKey("user.user_id"),
        nullable=False,
    )

    # ----------------------
    # 🔗 Relationships
    # ----------------------

    vendor: Mapped["Vendor"] = relationship(
        "Vendor",
        foreign_keys=[assigned_vendor],
    )

    well: Mapped["Well"] = relationship(
        "Well",
        foreign_keys=[well_id],
    )