from datetime import datetime, timedelta
from decimal import Decimal
import enum
from typing import TYPE_CHECKING
from sqlalchemy import Boolean, DateTime, Enum, Float, ForeignKey, Interval, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.base import BaseModel
from app.functions import generate_uuid, utc_now

if TYPE_CHECKING:
    from app.blueprints.services.model import Service
    from app.blueprints.user.model import User
    from app.blueprints.vendor.model import Vendor
    from app.blueprints.well.model import Well


def enum_values(enum_class: type[enum.Enum]) -> list[str]:
    return [member.value for member in enum_class]

class OrderStatus(enum.Enum):
    PENDING = "Pending"
    ASSIGNED = "Assigned"
    IN_PROGRESS = "In Progress"
    COMPLETED = "Completed"
    CANCELLED = "Cancelled"

class PriorityStatus(enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class LocationType(enum.Enum):
    WELL = "WELL"
    GPS = "GPS"
    ADDRESS = "ADDRESS"


class FrequencyType(enum.Enum):
    ONE_TIME = "ONE_TIME"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"

#work order id is a string because it will be a uuid generated by the backend, not an auto-incrementing integer. 
# This is for better scalability and uniqueness
class WorkOrder(BaseModel):
    __tablename__ = "work_orders"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=generate_uuid,
    )

    assigned_vendor: Mapped[str | None] = mapped_column(
        ForeignKey("vendor.id"),
        nullable=True,
    )

    client_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
    )

    assigned_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    description: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
    )

    estimated_start_date: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    estimated_end_date: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    current_status: Mapped[OrderStatus] = mapped_column(
        Enum(
            OrderStatus,
            name="order_status",
            values_callable=enum_values,
        ),
        nullable=False,
    )

    comments: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
    )
    location: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    location_type: Mapped[LocationType | None] = mapped_column(
        Enum(
            LocationType,
            name="location_type",
            values_callable=enum_values,
        ),
        nullable=True,
    )

    latitude: Mapped[Decimal | None] = mapped_column(
        Numeric,
        nullable=True,
    )

    longitude: Mapped[Decimal | None] = mapped_column(
        Numeric,
        nullable=True,
    )

    estimated_cost: Mapped[Decimal | None] = mapped_column(
        Numeric,
        nullable=True,
    )

    estimated_duration: Mapped[timedelta | None] = mapped_column(
        Interval,
        nullable=True,
    )

    priority: Mapped[PriorityStatus] = mapped_column(
        Enum(
            PriorityStatus,
            name="priority_status",
            values_callable=enum_values,
        ),
        nullable=False,
    )

    well_id: Mapped[str | None] = mapped_column(
        ForeignKey("well.id"),
        nullable=True,
    )

    service_type: Mapped[str | None] = mapped_column(
        ForeignKey("services.id"),
        nullable=True,
    )

    estimated_quantity: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    units: Mapped[str | None] = mapped_column(
        String(15),
        nullable=True,
    )

    is_recurring: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
    )

    recurrence_type: Mapped[FrequencyType | None] = mapped_column(
        Enum(
            FrequencyType,
            name="frequency_type",
            values_callable=enum_values,
        ),
        nullable=True,
    )

    cancelled_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    cancellation_reason: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
    )

    # ----------------------
    # 🔗 Relationships
    # ----------------------

    vendor: Mapped["Vendor | None"] = relationship(
        "Vendor",
        foreign_keys=[assigned_vendor],
        back_populates="work_orders",
    )

    well: Mapped["Well | None"] = relationship(
        "Well",
        foreign_keys=[well_id],
    )

    service: Mapped["Service | None"] = relationship(
        "Service",
        foreign_keys=[service_type],
    )
