"""add vendor_code to vendor

Revision ID: 047baf28638a
Revises: 
Create Date: 2026-04-12 23:21:29.501772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047baf28638a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('updated_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['created_by_user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'user', ['updated_by_user_id'], ['user_id'])

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_code', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['vendor_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('vendor_code')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_by_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
